package cloudevents

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel/attribute"

	"github.com/YipYap-run/YipYap-FOSS/internal/bus"
	"github.com/YipYap-run/YipYap-FOSS/internal/crypto"
	"github.com/YipYap-run/YipYap-FOSS/internal/domain"
	"github.com/YipYap-run/YipYap-FOSS/internal/store"
	"github.com/YipYap-run/YipYap-FOSS/internal/telemetry"
)

// routerSubject is the wildcard subscription the Router uses to pick up
// every CloudEvent emitted by yipyap internals. The NATS-style ">"
// wildcard matches any trailing token sequence; the ChannelBus fallback
// implements the same semantics.
const routerSubject = "events.cloudevents.out.>"

// routerQueueGroup ensures that when multiple notifier replicas run, each
// CloudEvent is fanned out to cloudevent_http channels by exactly one
// router instance rather than every replica.
const routerQueueGroup = "cloudevent-router"

// Router bridges the CloudEvents egress tree to the notification dispatcher.
//
// It subscribes to the wildcard subject `events.cloudevents.out.>`. For each
// event it receives, it looks up every `cloudevent_http` NotificationChannel
// in the event's org and publishes a domain.NotificationJob to
// `notify.request` per channel. The existing dispatcher then routes those
// jobs to the cloudevent_http provider's worker pool.
//
// Note: domain.NotificationJob's Message field carries the raw CloudEvent
// structured-mode JSON envelope for cloudevent_http channels. For all other
// channel types, Message holds human-readable alert text generated by the
// escalation engine. The dispatcher routes solely on job.Channel, so the
// two Message formats coexist without conflict.
type Router struct {
	bus      bus.Bus
	store    store.Store
	outbox   store.OutboxStore
	envelope *crypto.Envelope
	metrics  *telemetry.Metrics
}

// RouterOption configures a Router at construction time.
type RouterOption func(*Router)

// WithRouterMetrics wires telemetry.Metrics into the router for span
// enrichment and dead-letter accounting. Nil disables recording.
func WithRouterMetrics(m *telemetry.Metrics) RouterOption {
	return func(r *Router) { r.metrics = m }
}

// NewRouter constructs a Router. `outbox` may be nil (FOSS/standalone with no
// durability backing). `envelope` may be nil, in which case channel configs
// are forwarded with the plaintext (0x00) version byte.
func NewRouter(b bus.Bus, s store.Store, outbox store.OutboxStore, envelope *crypto.Envelope, opts ...RouterOption) *Router {
	r := &Router{bus: b, store: s, outbox: outbox, envelope: envelope}
	for _, opt := range opts {
		if opt != nil {
			opt(r)
		}
	}
	return r
}

// SetMetrics wires (or replaces) the telemetry bundle on an existing Router.
// Safe to call with nil to disable recording.
func (r *Router) SetMetrics(m *telemetry.Metrics) {
	if r == nil {
		return
	}
	r.metrics = m
}

// Start subscribes the router to the CloudEvents egress subject tree.
// The subscription is installed with a queue group so that multi-replica
// notifier deployments fan out each event exactly once. Start returns as
// soon as the subscription is registered; message handling runs in the
// bus implementation's handler goroutines.
func (r *Router) Start(ctx context.Context) error {
	return r.bus.QueueSubscribe(routerSubject, routerQueueGroup, func(hctx context.Context, subject string, data []byte) error {
		r.handle(hctx, subject, data)
		// Never return an error from the handler: Router failures are
		// logged and the message is considered delivered. In a durable
		// NATS backend, returning nil lets the consumer progress rather
		// than trigger redelivery, which a route failure cannot fix on
		// its own (the fan-out job publish is best-effort per channel).
		return nil
	})
}

// Stop is a no-op for now. The Bus interface does not expose per-subscription
// teardown; the caller disposes of the bus to release the subscription.
func (r *Router) Stop() {}

// handle processes one CloudEvent delivery.
func (r *Router) handle(ctx context.Context, subject string, data []byte) {
	ctx, span := tracer.Start(ctx, "cloudevents.router.fanout")
	defer span.End()
	span.SetAttributes(attribute.String("subject", subject))

	// Populate ce.type / ce.id from the structured envelope best-effort.
	ceType, ceID := extractEventTypeAndID(data)
	if ceType != "" {
		span.SetAttributes(attribute.String("ce.type", ceType))
	}
	if ceID != "" {
		span.SetAttributes(attribute.String("ce.id", ceID))
	}

	orgID, ok := extractOrgID(subject)
	if !ok {
		slog.Warn("cloudevent-router: malformed subject", "subject", subject)
		span.SetAttributes(attribute.String("error", "malformed subject"))
		return
	}
	span.SetAttributes(attribute.String("org.id", orgID))

	channels, err := r.store.NotificationChannels().ListByOrg(ctx, orgID, store.ListParams{Limit: 1000})
	if err != nil {
		slog.Error("cloudevent-router: list channels", "org_id", orgID, "error", err)
		span.RecordError(err)
		return
	}

	matched := 0
	defer func() {
		span.SetAttributes(attribute.Int("channels.matched", matched))
	}()

	for _, ch := range channels {
		if ch == nil {
			continue
		}
		if ch.Type != "cloudevent_http" || !ch.Enabled {
			continue
		}
		matched++

		versionedConfig, err := r.encodeConfig(ch.Config)
		if err != nil {
			slog.Error("cloudevent-router: encode channel config",
				"channel_id", ch.ID, "error", err)
			continue
		}

		// Extract CE ID for dedup; fall back to channel ID + subject hash
		// if the envelope cannot be parsed.
		ceID := extractEventID(data)

		job := domain.NotificationJob{
			ID:      uuid.New().String(),
			AlertID: "",
			OrgID:   orgID,
			Channel: "cloudevent_http",
			// TargetConfig is base64(version-byte || config-bytes) per the
			// engine's convention so the dispatcher/provider decryption
			// path is identical for alert-state and cloudevent jobs.
			TargetConfig: base64.StdEncoding.EncodeToString(versionedConfig),
			// Message is the structured-mode CloudEvent JSON envelope
			// passed through verbatim. The cloudevent_http provider
			// re-parses it to honor event_types filters and drive the
			// ce.Event HTTP send.
			Message:   string(data),
			DedupeKey: fmt.Sprintf("%s-%s", orgID, ceID),
		}

		payload, err := json.Marshal(job)
		if err != nil {
			slog.Error("cloudevent-router: marshal job", "error", err)
			continue
		}

		// Dual-write: outbox for durability, bus for fast-path delivery.
		// Mirrors the Engine pattern so the existing outbox poller will
		// reclaim a stuck job if the dispatcher crashes mid-send.
		if r.outbox != nil {
			if err := r.outbox.Enqueue(ctx, job.ID, string(payload)); err != nil {
				slog.Warn("cloudevent-router: outbox enqueue", "error", err)
			}
		}

		if err := r.bus.PublishDurable(ctx, "notify.request", payload, job.ID); err != nil {
			slog.Error("cloudevent-router: publish notify.request",
				"job_id", job.ID, "channel_id", ch.ID, "error", err)
		}
	}
}

// encodeConfig prepends the version byte used by the notify provider config
// decoder: 0x00 for plaintext, 0x01 for envelope-encrypted.
func (r *Router) encodeConfig(cfg string) ([]byte, error) {
	if r.envelope != nil {
		enc, err := r.envelope.Encrypt([]byte(cfg))
		if err != nil {
			return nil, err
		}
		return append([]byte{0x01}, enc...), nil
	}
	return append([]byte{0x00}, []byte(cfg)...), nil
}

// extractOrgID pulls the {orgID} token from subjects of the form
// "events.cloudevents.out.{orgID}.{type...}". Returns ok=false if the
// subject does not have the required prefix or is missing the org segment.
func extractOrgID(subject string) (string, bool) {
	parts := strings.Split(subject, ".")
	// Required: ["events","cloudevents","out",orgID, ...type segments]
	if len(parts) < 5 {
		return "", false
	}
	if parts[0] != "events" || parts[1] != "cloudevents" || parts[2] != "out" {
		return "", false
	}
	if parts[3] == "" {
		return "", false
	}
	return parts[3], true
}

// extractEventID pulls the "id" field from a CloudEvent structured-mode
// JSON envelope. Returns empty string on any parse error; callers fall
// back to a job-local dedup key.
func extractEventID(data []byte) string {
	_, id := extractEventTypeAndID(data)
	return id
}

// extractEventTypeAndID pulls the "type" and "id" fields from a CloudEvent
// structured-mode JSON envelope. Either may be empty on parse error.
func extractEventTypeAndID(data []byte) (string, string) {
	var env struct {
		Type string `json:"type"`
		ID   string `json:"id"`
	}
	if err := json.Unmarshal(data, &env); err != nil {
		return "", ""
	}
	return env.Type, env.ID
}
