// Code generated by internal/cloudevents/gen. DO NOT EDIT.

export const TypeAlertAcknowledgedV1 = "run.yipyap.alert.acknowledged.v1";

export interface AlertAcknowledgedV1Data {
  alert_id: string;
  monitor_id: string;
  acked_by: string;
  acked_at: string;
}

export const TypeAlertEscalatedV1 = "run.yipyap.alert.escalated.v1";

export interface AlertEscalatedV1Data {
  alert_id: string;
  monitor_id: string;
  step_index: number;
  to_channel: string;
  escalated_at: string;
}

export const TypeAlertFiredV1 = "run.yipyap.alert.fired.v1";

export interface AlertFiredV1Data {
  alert_id: string;
  monitor_id: string;
  severity: "info" | "warning" | "critical";
  reason: string;
  fired_at: string;
}

export const TypeAlertResolvedV1 = "run.yipyap.alert.resolved.v1";

export interface AlertResolvedV1Data {
  alert_id: string;
  monitor_id: string;
  resolved_by?: string;
  resolved_at: string;
}

export const TypeIngestHeartbeatV1 = "run.yipyap.ingest.heartbeat.v1";

export interface IngestHeartbeatV1Data {
  note?: string;
}

export const TypeIngestStatusV1 = "run.yipyap.ingest.status.v1";

export interface IngestStatusV1Data {
  status: "up" | "down" | "degraded";
  message?: string;
}

export const TypeMaintenanceEndedV1 = "run.yipyap.maintenance.ended.v1";

export interface MaintenanceEndedV1Data {
  window_id: string;
  ended_at: string;
  ended_early?: boolean;
}

export const TypeMaintenanceStartedV1 = "run.yipyap.maintenance.started.v1";

export interface MaintenanceStartedV1Data {
  window_id: string;
  monitors: string[];
  started_at: string;
  scheduled_end?: string;
}

export const TypeMonitorDegradedV1 = "run.yipyap.monitor.degraded.v1";

export interface MonitorDegradedV1Data {
  monitor_id: string;
  check_id: string;
  reason: string;
  checked_at: string;
}

export const TypeMonitorDownV1 = "run.yipyap.monitor.down.v1";

export interface MonitorDownV1Data {
  monitor_id: string;
  check_id: string;
  failure_reason: string;
  checked_at: string;
}

export const TypeMonitorHeartbeatMissedV1 = "run.yipyap.monitor.heartbeat_missed.v1";

export interface MonitorHeartbeatMissedV1Data {
  monitor_id: string;
  expected_by: string;
  last_seen_at?: string;
}

export const TypeMonitorUpV1 = "run.yipyap.monitor.up.v1";

export interface MonitorUpV1Data {
  monitor_id: string;
  check_id: string;
  latency_ms?: number;
  checked_at: string;
}

export const TypeReplyAlertAckWithContextV1 = "run.yipyap.reply.alert.ack_with_context.v1";

export interface ReplyAlertAckWithContextV1Data {
  alert_id: string;
  reason_code: "resolved_by_deploy" | "duplicate_of" | "known_issue" | "investigating" | "false_positive" | "transient" | "other";
  note?: string;
  reference_id?: string;
}

export const TypeReplyAlertClaimedV1 = "run.yipyap.reply.alert.claimed.v1";

export interface ReplyAlertClaimedV1Data {
  alert_id: string;
  who: string;
  claimed_at: string;
  note?: string;
}

export const TypeReplyAlertDeduplicatedV1 = "run.yipyap.reply.alert.deduplicated.v1";

export interface ReplyAlertDeduplicatedV1Data {
  alert_id: string;
  duplicate_of: string;
  reason: string;
}

export const TypeReplyAlertEnrichedV1 = "run.yipyap.reply.alert.enriched.v1";

export interface ReplyAlertEnrichedV1Data {
  alert_id: string;
  attachments: Record<string, unknown>[];
}

export const TypeReplyAlertEscalatedV1 = "run.yipyap.reply.alert.escalated.v1";

export interface ReplyAlertEscalatedV1Data {
  alert_id: string;
  new_severity?: "info" | "warning" | "critical";
  step_index?: number;
  reason: string;
}

export const TypeReplyAlertLinkedV1 = "run.yipyap.reply.alert.linked.v1";

export interface ReplyAlertLinkedV1Data {
  alert_id: string;
  kind: "jira" | "pagerduty" | "slack_thread" | "github_issue" | "gitlab_issue" | "linear" | "servicenow" | "other";
  id: string;
  url?: string;
  title?: string;
}

export const TypeReplyAlertOwnershipV1 = "run.yipyap.reply.alert.ownership.v1";

export interface ReplyAlertOwnershipV1Data {
  alert_id: string;
  owner_kind: "team" | "user";
  owner_id: string;
  reason?: string;
}

export const TypeReplyAlertRemediationResultV1 = "run.yipyap.reply.alert.remediation_result.v1";

export interface ReplyAlertRemediationResultV1Data {
  alert_id: string;
  remediation_id: string;
  outcome: "success" | "failure" | "partial";
  message: string;
  artifact_url?: string;
}

export const TypeReplyAlertRemediationStartedV1 = "run.yipyap.reply.alert.remediation_started.v1";

export interface ReplyAlertRemediationStartedV1Data {
  alert_id: string;
  remediation_id: string;
  description: string;
  expected_duration_seconds?: number;
}

export const TypeReplyAlertRouteV1 = "run.yipyap.reply.alert.route.v1";

export interface ReplyAlertRouteV1Data {
  alert_id: string;
  target_channel_id: string;
  match_filter: Record<string, unknown>;
  expires_at: string;
  reason: string;
}

export const TypeReplyAlertStatusPageV1 = "run.yipyap.reply.alert.status_page.v1";

export interface ReplyAlertStatusPageV1Data {
  alert_id: string;
  provider: "statuspage_io" | "instatus" | "atlassian_statuspage" | "cachet" | "custom";
  url: string;
  public_message: string;
  updated_at: string;
}

export const TypeReplyAlertSuppressedV1 = "run.yipyap.reply.alert.suppressed.v1";

export interface ReplyAlertSuppressedV1Data {
  alert_id: string;
  duration_seconds: number;
  reason: string;
  match_filter?: Record<string, unknown>;
}

export const TypeReplyMonitorDeregisterV1 = "run.yipyap.reply.monitor.deregister.v1";

export interface ReplyMonitorDeregisterV1Data {
  alert_id: string;
  monitor_id: string;
  reason: string;
}
