// Code generated by internal/cloudevents/gen. DO NOT EDIT.

package types

import (
	"time"
)

var _ = time.Time{}

const TypeAlertAcknowledgedV1 = "run.yipyap.alert.acknowledged.v1"

type AlertAcknowledgedV1Data struct {
	AlertID   string    `json:"alert_id"`
	MonitorID string    `json:"monitor_id"`
	AckedBy   string    `json:"acked_by"`
	AckedAt   time.Time `json:"acked_at"`
}

const TypeAlertEscalatedV1 = "run.yipyap.alert.escalated.v1"

type AlertEscalatedV1Data struct {
	AlertID     string    `json:"alert_id"`
	MonitorID   string    `json:"monitor_id"`
	StepIndex   int64     `json:"step_index"`
	ToChannel   string    `json:"to_channel"`
	EscalatedAt time.Time `json:"escalated_at"`
}

const TypeAlertFiredV1 = "run.yipyap.alert.fired.v1"

type AlertFiredV1Data struct {
	AlertID   string    `json:"alert_id"`
	MonitorID string    `json:"monitor_id"`
	Severity  string    `json:"severity"`
	Reason    string    `json:"reason"`
	FiredAt   time.Time `json:"fired_at"`
}

const TypeAlertResolvedV1 = "run.yipyap.alert.resolved.v1"

type AlertResolvedV1Data struct {
	AlertID    string    `json:"alert_id"`
	MonitorID  string    `json:"monitor_id"`
	ResolvedBy string    `json:"resolved_by,omitempty"`
	ResolvedAt time.Time `json:"resolved_at"`
}

const TypeIngestHeartbeatV1 = "run.yipyap.ingest.heartbeat.v1"

type IngestHeartbeatV1Data struct {
	Note string `json:"note,omitempty"`
}

const TypeIngestStatusV1 = "run.yipyap.ingest.status.v1"

type IngestStatusV1Data struct {
	Status  string `json:"status"`
	Message string `json:"message,omitempty"`
}

const TypeMaintenanceEndedV1 = "run.yipyap.maintenance.ended.v1"

type MaintenanceEndedV1Data struct {
	WindowID   string    `json:"window_id"`
	EndedAt    time.Time `json:"ended_at"`
	EndedEarly bool      `json:"ended_early,omitempty"`
}

const TypeMaintenanceStartedV1 = "run.yipyap.maintenance.started.v1"

type MaintenanceStartedV1Data struct {
	WindowID     string    `json:"window_id"`
	Monitors     []string  `json:"monitors"`
	StartedAt    time.Time `json:"started_at"`
	ScheduledEnd time.Time `json:"scheduled_end,omitempty"`
}

const TypeMonitorDegradedV1 = "run.yipyap.monitor.degraded.v1"

type MonitorDegradedV1Data struct {
	MonitorID string    `json:"monitor_id"`
	CheckID   string    `json:"check_id"`
	Reason    string    `json:"reason"`
	CheckedAt time.Time `json:"checked_at"`
}

const TypeMonitorDownV1 = "run.yipyap.monitor.down.v1"

type MonitorDownV1Data struct {
	MonitorID     string    `json:"monitor_id"`
	CheckID       string    `json:"check_id"`
	FailureReason string    `json:"failure_reason"`
	CheckedAt     time.Time `json:"checked_at"`
}

const TypeMonitorHeartbeatMissedV1 = "run.yipyap.monitor.heartbeat_missed.v1"

type MonitorHeartbeatMissedV1Data struct {
	MonitorID  string    `json:"monitor_id"`
	ExpectedBy time.Time `json:"expected_by"`
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
}

const TypeMonitorUpV1 = "run.yipyap.monitor.up.v1"

type MonitorUpV1Data struct {
	MonitorID string    `json:"monitor_id"`
	CheckID   string    `json:"check_id"`
	LatencyMs int64     `json:"latency_ms,omitempty"`
	CheckedAt time.Time `json:"checked_at"`
}

const TypeReplyAlertAckWithContextV1 = "run.yipyap.reply.alert.ack_with_context.v1"

type ReplyAlertAckWithContextV1Data struct {
	AlertID     string `json:"alert_id"`
	ReasonCode  string `json:"reason_code"`
	Note        string `json:"note,omitempty"`
	ReferenceID string `json:"reference_id,omitempty"`
}

const TypeReplyAlertClaimedV1 = "run.yipyap.reply.alert.claimed.v1"

type ReplyAlertClaimedV1Data struct {
	AlertID   string    `json:"alert_id"`
	Who       string    `json:"who"`
	ClaimedAt time.Time `json:"claimed_at"`
	Note      string    `json:"note,omitempty"`
}

const TypeReplyAlertDeduplicatedV1 = "run.yipyap.reply.alert.deduplicated.v1"

type ReplyAlertDeduplicatedV1Data struct {
	AlertID     string `json:"alert_id"`
	DuplicateOf string `json:"duplicate_of"`
	Reason      string `json:"reason"`
}

const TypeReplyAlertEnrichedV1 = "run.yipyap.reply.alert.enriched.v1"

type ReplyAlertEnrichedV1Data struct {
	AlertID     string           `json:"alert_id"`
	Attachments []map[string]any `json:"attachments"`
}

const TypeReplyAlertEscalatedV1 = "run.yipyap.reply.alert.escalated.v1"

type ReplyAlertEscalatedV1Data struct {
	AlertID     string `json:"alert_id"`
	NewSeverity string `json:"new_severity,omitempty"`
	StepIndex   int64  `json:"step_index,omitempty"`
	Reason      string `json:"reason"`
}

const TypeReplyAlertLinkedV1 = "run.yipyap.reply.alert.linked.v1"

type ReplyAlertLinkedV1Data struct {
	AlertID string `json:"alert_id"`
	Kind    string `json:"kind"`
	ID      string `json:"id"`
	URL     string `json:"url,omitempty"`
	Title   string `json:"title,omitempty"`
}

const TypeReplyAlertOwnershipV1 = "run.yipyap.reply.alert.ownership.v1"

type ReplyAlertOwnershipV1Data struct {
	AlertID   string `json:"alert_id"`
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
	Reason    string `json:"reason,omitempty"`
}

const TypeReplyAlertRemediationResultV1 = "run.yipyap.reply.alert.remediation_result.v1"

type ReplyAlertRemediationResultV1Data struct {
	AlertID       string `json:"alert_id"`
	RemediationID string `json:"remediation_id"`
	Outcome       string `json:"outcome"`
	Message       string `json:"message"`
	ArtifactURL   string `json:"artifact_url,omitempty"`
}

const TypeReplyAlertRemediationStartedV1 = "run.yipyap.reply.alert.remediation_started.v1"

type ReplyAlertRemediationStartedV1Data struct {
	AlertID                 string `json:"alert_id"`
	RemediationID           string `json:"remediation_id"`
	Description             string `json:"description"`
	ExpectedDurationSeconds int64  `json:"expected_duration_seconds,omitempty"`
}

const TypeReplyAlertRouteV1 = "run.yipyap.reply.alert.route.v1"

type ReplyAlertRouteV1Data struct {
	AlertID         string         `json:"alert_id"`
	TargetChannelID string         `json:"target_channel_id"`
	MatchFilter     map[string]any `json:"match_filter"`
	ExpiresAt       time.Time      `json:"expires_at"`
	Reason          string         `json:"reason"`
}

const TypeReplyAlertStatusPageV1 = "run.yipyap.reply.alert.status_page.v1"

type ReplyAlertStatusPageV1Data struct {
	AlertID       string    `json:"alert_id"`
	Provider      string    `json:"provider"`
	URL           string    `json:"url"`
	PublicMessage string    `json:"public_message"`
	UpdatedAt     time.Time `json:"updated_at"`
}

const TypeReplyAlertSuppressedV1 = "run.yipyap.reply.alert.suppressed.v1"

type ReplyAlertSuppressedV1Data struct {
	AlertID         string         `json:"alert_id"`
	DurationSeconds int64          `json:"duration_seconds"`
	Reason          string         `json:"reason"`
	MatchFilter     map[string]any `json:"match_filter,omitempty"`
}

const TypeReplyMonitorDeregisterV1 = "run.yipyap.reply.monitor.deregister.v1"

type ReplyMonitorDeregisterV1Data struct {
	AlertID   string `json:"alert_id"`
	MonitorID string `json:"monitor_id"`
	Reason    string `json:"reason"`
}
